MERGE INTO ADM_OPERATION A USING dual ON (A.OPER_CODE = '99990020') WHEN NOT MATCHED THEN INSERT (Oper_Code, Name, Name2, Sys_No,Func_Name, Lookup,Audit_level, Log_Req_Data, Log_Res_Data) Values('99990020',UPPER('Хүмүүсийн төгссөн сургуулийн жагсаалт'),'',9999,'selectDemoPerson','java:global/nes/demo.person.EJB/DemoParam!mn.grapecity.nes.demo.person.PersonParamRemote',1,1,0) WHEN MATCHED THEN UPDATE SET LOOKUP = 'java:global/nes/demo.person.EJB/DemoParam!mn.grapecity.nes.demo.person.PersonParamRemote', NAME = UPPER('Хүмүүсийн төгссөн сургуулийн жагсаалт'), NAME2 = '', FUNC_NAME = 'selectDemoPerson'~~
MERGE INTO ADM_OPERATION A USING dual ON (A.OPER_CODE = '99990021') WHEN NOT MATCHED THEN INSERT (Oper_Code, Name, Name2, Sys_No,Func_Name, Lookup,Audit_level, Log_Req_Data, Log_Res_Data) Values('99990021',UPPER('Хүмүүсийн төгссөн сургуулийн бүртгэх'),'',9999,'insertDemoPerson','java:global/nes/demo.person.EJB/DemoParam!mn.grapecity.nes.demo.person.PersonParamRemote',1,1,0) WHEN MATCHED THEN UPDATE SET LOOKUP = 'java:global/nes/demo.person.EJB/DemoParam!mn.grapecity.nes.demo.person.PersonParamRemote', NAME = UPPER('Хүмүүсийн төгссөн сургуулийг бүртгэх'), NAME2 = '', FUNC_NAME = 'insertDemoPerson'~~
MERGE INTO ADM_OPERATION A USING dual ON (A.OPER_CODE = '99990022') WHEN NOT MATCHED THEN INSERT (Oper_Code, Name, Name2, Sys_No,Func_Name, Lookup,Audit_level, Log_Req_Data, Log_Res_Data) Values('99990022',UPPER('Хүмүүсийн төгссөн сургууль засах'),'',9999,'updateDemoPerson','java:global/nes/demo.person.EJB/DemoParam!mn.grapecity.nes.demo.person.PersonParamRemote',1,1,0) WHEN MATCHED THEN UPDATE SET LOOKUP = 'java:global/nes/demo.person.EJB/DemoParam!mn.grapecity.nes.demo.person.PersonParamRemote', NAME = UPPER('Хүмүүсийн төгссөн сургууль засах'), NAME2 = '', FUNC_NAME = 'updateDemoPerson'~~
MERGE INTO ADM_OPERATION A USING dual ON (A.OPER_CODE = '99990023') WHEN NOT MATCHED THEN INSERT (Oper_Code, Name, Name2, Sys_No,Func_Name, Lookup,Audit_level, Log_Req_Data, Log_Res_Data) Values('99990023',UPPER('Хүмүүсийн төгссөн сургууль устгах'),'',9999,'deleteDemoPerson','java:global/nes/demo.person.EJB/DemoParam!mn.grapecity.nes.demo.person.PersonParamRemote',1,1,0) WHEN MATCHED THEN UPDATE SET LOOKUP = 'java:global/nes/demo.person.EJB/DemoParam!mn.grapecity.nes.demo.person.PersonParamRemote', NAME = UPPER('Хүмүүсийн төгссөн сургууль устгах'), NAME2 = '', FUNC_NAME = 'deleteDemoPerson'~~
MERGE INTO ADM_OPERATION A USING dual ON (A.OPER_CODE = '99990024') WHEN NOT MATCHED THEN INSERT (Oper_Code, Name, Name2, Sys_No,Func_Name, Lookup,Audit_level, Log_Req_Data, Log_Res_Data) Values('99990024',UPPER('Хүмүүсийн төгссөн сургуулийн дэлгэрэнгүй'),'',9999,'detailNetwork','java:global/nes/demo.person.EJB/DemoParam!mn.grapecity.nes.demo.person.PersonParamRemote',1,1,0) WHEN MATCHED THEN UPDATE SET LOOKUP = 'java:global/nes/demo.person.EJB/DemoParam!mn.grapecity.nes.demo.person.PersonParamRemote', NAME = UPPER('Хүмүүсийн төгссөн сургуулийн дэлгэрэнгүй'), NAME2 = '', FUNC_NAME = 'detailDemoPerson'~~

MERGE INTO ADM_PRIVILEGE  A USING dual ON (A.PRIV_CODE = '99990020') WHEN NOT MATCHED THEN INSERT  (PRIV_CODE, NAME, NAME2, SYS_NO) VALUES('99990020','Хүмүүсийн төгссөн сургуулийн жагсаалт','',9999)~~
MERGE INTO ADM_PRIVILEGE  A USING dual ON (A.PRIV_CODE = '99990021') WHEN NOT MATCHED THEN INSERT  (PRIV_CODE, NAME, NAME2, SYS_NO) VALUES('99990021','Хүмүүсийн төгссөн сургуулийг бүртгэх','',9999)~~
MERGE INTO ADM_PRIVILEGE  A USING dual ON (A.PRIV_CODE = '99990022') WHEN NOT MATCHED THEN INSERT  (PRIV_CODE, NAME, NAME2, SYS_NO) VALUES('99990022','Хүмүүсийн төгссөн сургууль засах','',9999)~~
MERGE INTO ADM_PRIVILEGE  A USING dual ON (A.PRIV_CODE = '99990023') WHEN NOT MATCHED THEN INSERT  (PRIV_CODE, NAME, NAME2, SYS_NO) VALUES('99990023','Хүмүүсийн төгссөн сургууль устгах','',9999)~~
MERGE INTO ADM_PRIVILEGE  A USING dual ON (A.PRIV_CODE = '99990024') WHEN NOT MATCHED THEN INSERT  (PRIV_CODE, NAME, NAME2, SYS_NO) VALUES('99990024','Хүмүүсийн төгссөн сургуулийн дэлгэрэнгүй','',9999)~~

MERGE INTO ADM_OPER_PRIV A USING dual ON (A.PRIV_CODE = '99990020' AND A.OPER_CODE = '99990020') WHEN NOT MATCHED THEN INSERT (OPER_CODE, PRIV_CODE) VALUES('99990020','99990020')~~
MERGE INTO ADM_OPER_PRIV A USING dual ON (A.PRIV_CODE = '99990021' AND A.OPER_CODE = '99990021') WHEN NOT MATCHED THEN INSERT (OPER_CODE, PRIV_CODE) VALUES('99990021','99990021')~~
MERGE INTO ADM_OPER_PRIV A USING dual ON (A.PRIV_CODE = '99990021' AND A.OPER_CODE = '99990022') WHEN NOT MATCHED THEN INSERT (OPER_CODE, PRIV_CODE) VALUES('99990022','99990021')~~
MERGE INTO ADM_OPER_PRIV A USING dual ON (A.PRIV_CODE = '99990021' AND A.OPER_CODE = '99990023') WHEN NOT MATCHED THEN INSERT (OPER_CODE, PRIV_CODE) VALUES('99990023','99990021')~~
MERGE INTO ADM_OPER_PRIV A USING dual ON (A.PRIV_CODE = '99990020' AND A.OPER_CODE = '99990024') WHEN NOT MATCHED THEN INSERT (OPER_CODE, PRIV_CODE) VALUES('99990024','99990020')~~