/*SRC_DEMO_SCHOOL$20200423000001.sql*/
DECLARE BEGIN 
	IF (CHK_TBL('DEMO_SCHOOL') <= 0) THEN 
		EXECUTE IMMEDIATE ' CREATE TABLE DEMO_SCHOOL(DEMOID NUMBER(20,0) NOT NULL)'; 
	END IF;
END; ~~
DECLARE BEGIN IF (CHK_COL('DEMO_SCHOOL','DEMOID') <= 0) THEN EXECUTE IMMEDIATE 'ALTER TABLE DEMO_SCHOOL ADD DEMOID NUMBER(20,0) NOT NULL'; END IF;END;~~
DECLARE BEGIN IF (CHK_COL('DEMO_SCHOOL','SCHOOLUSERID') <= 0) THEN EXECUTE IMMEDIATE 'ALTER TABLE DEMO_SCHOOL ADD SCHOOLUSERID VARCHAR2(200) NOT NULL'; END IF;END;~~
DECLARE BEGIN IF (CHK_COL('DEMO_SCHOOL','USERID') <= 0) THEN EXECUTE IMMEDIATE 'ALTER TABLE DEMO_SCHOOL ADD USERID NUMBER(20,0) NOT NULL'; END IF;END;~~
DECLARE BEGIN IF (CHK_COL('DEMO_SCHOOL','STARTDATE') <= 0) THEN EXECUTE IMMEDIATE 'ALTER TABLE DEMO_SCHOOL ADD STARTDATE DATE'; END IF;END;~~
DECLARE BEGIN IF (CHK_COL('DEMO_SCHOOL','ENDDATE') <= 0) THEN EXECUTE IMMEDIATE 'ALTER TABLE DEMO_SCHOOL ADD ENDDATE DATE'; END IF;END;~~
DECLARE BEGIN IF (CHK_COL('DEMO_SCHOOL','GRADEPOINT') <= 0) THEN EXECUTE IMMEDIATE 'ALTER TABLE DEMO_SCHOOL ADD GRADEPOINT DOUBLE'; END IF;END;~~
DECLARE BEGIN 
	IF (CHK_IX('PK_DEMO_SCHOOL') <= 0) THEN 
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX PK_DEMO_SCHOOL ON DEMO_SCHOOL(DEMOID)'; 
	END IF;
END; ~~	
DECLARE BEGIN 	
	IF (CHK_CNSTR('PK_DEMO_SCHOOL') <= 0) THEN 
		EXECUTE IMMEDIATE 'ALTER TABLE DEMO_SCHOOL ADD (CONSTRAINT PK_DEMO_SCHOOL PRIMARY KEY (DEMOID) USING INDEX PK_DEMO_SCHOOL ENABLE VALIDATE) '; 
	END IF;
END; ~~