MERGE INTO ADM_OPERATION a using dual on (a.oper_code='99990040') when matched then
 update set a.name=upper('????????? ???????? ?????'), sys_no=9999, func_name='selectDemoLesson', lookup='java:global/nes/demo.school.EJB/DemoParamLesson!mn.grapecity.nes.demo.school.SchoolParamRemote', audit_level=1,log_req_data=1, log_res_data=1 when not matched then
 insert(oper_code, name, name2, sys_no, func_name, lookup, audit_level, log_req_data, log_res_data) values('99990040', UPPER('????????? ???????? ?????'), UPPER('????????? ???????? ?????'), 9999, 'selectDemoLesson', 'java:global/nes/demo.school.EJB/DemoParamLesson!mn.grapecity.nes.demo.school.SchoolParamRemote', 1, 1, 0);
MERGE INTO ADM_OPERATION a using dual on (a.oper_code='99990041') when matched then
 update set a.name=upper('????????? ???????? ???????'), sys_no=9999, func_name='insertDemoLesson', lookup='java:global/nes/demo.school.EJB/DemoParamLesson!mn.grapecity.nes.demo.school.SchoolParamRemote', audit_level=1,log_req_data=1, log_res_data=1 when not matched then
 insert(oper_code, name, name2, sys_no, func_name, lookup, audit_level, log_req_data, log_res_data) values('99990041', UPPER('????????? ???????? ???????'), UPPER('????????? ???????? ???????'), 9999, 'insertDemoLesson', 'java:global/nes/demo.school.EJB/DemoParamLesson!mn.grapecity.nes.demo.school.SchoolParamRemote', 1, 1, 0);
MERGE INTO ADM_OPERATION a using dual on (a.oper_code='99990042') when matched then
 update set a.name=upper('????????? ???????? ?????????'), sys_no=9999, func_name='updateDemoLesson', lookup='java:global/nes/demo.school.EJB/DemoParamLesson!mn.grapecity.nes.demo.school.SchoolParamRemote', audit_level=1,log_req_data=1, log_res_data=1 when not matched then
 insert(oper_code, name, name2, sys_no, func_name, lookup, audit_level, log_req_data, log_res_data) values('99990042', UPPER('????????? ???????? ?????????'), UPPER('????????? ???????? ?????????'), 9999, 'updateDemoLesson', 'java:global/nes/demo.school.EJB/DemoParamLesson!mn.grapecity.nes.demo.school.SchoolParamRemote', 1, 1, 0);
MERGE INTO ADM_OPERATION a using dual on (a.oper_code='99990043') when matched then
 update set a.name=upper('?????? ??????'), sys_no=9999, func_name='deleteDemoLesson', lookup='java:global/nes/demo.school.EJB/DemoParamLesson!mn.grapecity.nes.demo.school.SchoolParamRemote', audit_level=1,log_req_data=1, log_res_data=1 when not matched
 then insert(oper_code, name, name2, sys_no, func_name, lookup, audit_level, log_req_data, log_res_data) values('99990043', UPPER('????????? ???????? ??????'), UPPER('????????? ???????? ??????'), 9999, 'deleteDemoLesson', 'java:global/nes/demo.school.EJB/DemoParamLesson!mn.grapecity.nes.demo.school.SchoolParamRemote', 1, 1, 0);
MERGE INTO ADM_OPERATION a using dual on (a.oper_code='99990044') when matched then
 update set a.name=upper('????????? ???????????'), sys_no=9999, func_name='detailDemoLesson', lookup='java:global/nes/demo.school.EJB/DemoParamLesson!mn.grapecity.nes.demo.school.SchoolParamRemote', audit_level=1,log_req_data=1, log_res_data=1 when not matched then
 insert(oper_code, name, name2, sys_no, func_name, lookup, audit_level, log_req_data, log_res_data) values('99990044', UPPER('????????? ???????????'), UPPER('????????? ???????????'), 9999, 'detailDemoLesson', 'java:global/nes/demo.school.EJB/DemoParamLesson!mn.grapecity.nes.demo.school.SchoolParamRemote', 1, 1, 0);